BUNDLES = [
    '//protocols/xmpp/core/api:onos-protocols-xmpp-core-api',
    '//protocols/xmpp/core/ctl:onos-protocols-xmpp-core-ctl',
    '//protocols/xmpp/pubsub/api:onos-protocols-xmpp-pubsub-api',
    '//protocols/xmpp/pubsub/ctl:onos-protocols-xmpp-pubsub-ctl',
    '//providers/xmpp/evpn/route:onos-providers-xmpp-evpn-route',
    '//providers/xmpp/evpn/host:onos-providers-xmpp-evpn-host',
    '//providers/xmpp/evpn/flow:onos-providers-xmpp-evpn-flow',
    '//apps/evpn-route-service/api:onos-apps-evpn-route-service-api',
    '//apps/routeserver:onos-apps-routeserver',
]

onos_app (
    app_name = 'org.onosproject.xmpp.evpn',
    title = 'XMPP EVPN Provider',
    category = 'Provider',
    url = 'http://onosproject.org',
    included_bundles = BUNDLES,
    description = 'XMPP protocol southbound provider for E-VPN.',
    required_apps = [
        'org.onosproject.xmpp.device',
        'org.onosproject.protocols.xmpp.pubsub',
    ]
)