COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:tinder-xmpp',
    '//protocols/xmpp/api:onos-protocols-xmpp-api',
]

BUNDLES = [
    ':onos-drivers-xmpp',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
#     test_deps = TEST_DEPS,
    resources_root = 'src/main/resources',
    resources = glob(['src/main/resources/**']),
)

onos_app (
    app_name = 'org.onosproject.drivers.xmpp',
    title = 'XMPP Device Drivers',
    category = 'Drivers',
    url = '',
    description = 'ONOS XMPP Device Drivers application.',
    included_bundles = BUNDLES,
    required_apps = [ 'org.onosproject.xmpp' ],
)
