COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//core/api:onos-api',
    '//lib:tinder-xmpp',
    '//protocols/xmpp/api:onos-protocols-xmpp-api',
    '//apps/pubsub:onos-apps-pubsub',
]

BUNDLES = [
    ':onos-drivers-opencontrail',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    #     test_deps = TEST_DEPS,
    resources_root = 'src/main/resources',
    resources = glob(['src/main/resources/**']),
)

onos_app (
    app_name = 'org.onosproject.drivers.opencontrail',
    title = 'OpenContrail XMPP Device Drivers',
    category = 'Drivers',
    url = '',
    description = 'OpenContrail XMPP Device Drivers application.',
    included_bundles = BUNDLES,
)

