COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//apps/pubsub-api:onos-apps-pubsub-api'
]

osgi_jar_with_tests(
    deps = COMPILE_DEPS,
)

onos_app (
    app_name = 'org.onosproject.contrail-poc',
    title = 'OpenContrail Networking PoC',
    category = 'PoC',
    url = 'http://onosproject.org',
    description = 'OpenContrail Networking Proof of Concept application.',
#     required_apps = [
#         'org.onosproject.pubsub-api'
#     ]
)