COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//protocols/xmpp/api:onos-protocols-xmpp-api',
    '//lib:netty-common',
    '//lib:netty-transport',
    '//lib:netty-buffer',
    '//lib:netty-codec',
    '//lib:org.apache.servicemix.bundles.dom4j',
    '//lib:tinder-xmpp',
    '//lib:stax2-api',
    '//lib:aalto-xml',
    '//lib:concurrent-hashmap',
    '//lib:gnu-idn',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
)