COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:tinder-xmpp',
    '//protocols/xmpp/api:onos-protocols-xmpp-api',
#     '//lib:netty-buffer',
    '//lib:netty-all',
#     '//lib:netty-transport',
#     '//lib:netty-transport-native-epoll',
#     '//lib:netty-handler',
#     '//lib:netty-resolver',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
)