COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:tinder-xmpp',
    '//incubator/api:onos-incubator-api',
    '//lib:org.apache.servicemix.bundles.dom4j',
    '//protocols/xmpp/core/api:onos-protocols-xmpp-core-api',
]

TEST_DEPS = [
    '//lib:TEST',
    '//core/api:onos-api-tests',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
)