BUNDLES = [
    '//lib:tinder-xmpp',
    '//lib:stax2-api',
    '//lib:aalto-xml',
    '//lib:org.apache.servicemix.bundles.dom4j',
    '//lib:concurrent-hashmap',
    '//lib:gnu-idn',
    '//protocols/xmpp/core/api:onos-protocols-xmpp-core-api',
]

# onos_app (
#     app_name = 'org.onosproject.xmpp',
#     title = 'XMPP Southbound Meta',
#     category = 'Provider',
#     url = 'http://onosproject.org',
#     description = 'ONOS XMPP southbound meta application',
#     included_bundles = [ '//utils/osgi:onlab-osgi' ],  # FIXME to allow hollow oar files
# #     required_apps = APPS,
# )
