COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:tinder-xmpp',
    '//protocols/xmpp/core/api:onos-protocols-xmpp-core-api',
    '//protocols/xmpp/core/ctl:onos-protocols-xmpp-core-ctl',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
)

onos_app (
    app_name = 'org.onosproject.xmpp.device',
    title = 'XMPP Device Provider',
    category = 'Provider',
    url = 'http://onosproject.org',
    description = 'XMPP protocol southbound provider.',
)