COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:tinder-xmpp',
    '//lib:org.apache.servicemix.bundles.dom4j',
    '//protocols/xmpp/pubsub/api:onos-protocols-xmpp-pubsub-api',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
)
