COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:KRYO',
    '//lib:org.apache.karaf.shell.console',
    '//cli:onos-cli',
    '//core/store/serializers:onos-core-serializers',
    '//apps/route-service/api:onos-apps-route-service-api',
    '//apps/evpn-route-service/api:onos-apps-evpn-route-service-api',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
    '//lib:TEST',
]

osgi_jar_with_tests(
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
)

onos_app(
    title = 'EVPN OpenContrail',
    category = 'Traffic Steering',
    url = 'http://onosproject.org',
    description = 'Ethernet VPN (EVPN) introduces a new model for Ethernet services delivery.' +
    'It enables integrated Layer 2 service over Ethernet with multihoming.',
    required_apps = [ 'org.onosproject.route-service', 'org.onosproject.evpn-route-service'],
)